# docker-compose.yml
version: '3.8'

services:
  web-mapper:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
      - WDS_SOCKET_HOST=localhost
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true